[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd shop-app && npm install && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }